title: Enza Deuscit
description: Psicologa, Psicoterapeuta Cognitivo-Comportamentale e Psicoterapeuta EMDR a Trento.
lang: it
url: ""
baseurl: ""
markdown: kramdown
exclude:
  - old
  - old-website
  - indicazioni

collections:
  appunti:
    output: true
    permalink: /appunti/:slug/
  storie:
    output: true
    permalink: /storie/:slug/

defaults:
  - scope:
      path: ""
      type: appunti
    values:
      layout: articolo
      section: Appunti di psicologia
      section_url: /appunti/
  - scope:
      path: ""
      type: storie
    values:
      layout: articolo
      section: Storie che scaldano il cuore
      section_url: /storie/
